# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculater(object):
    def setupUi(self, Calculater):
        Calculater.setObjectName("Calculater")
        Calculater.resize(524, 340)
        Calculater.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_six = QtWidgets.QPushButton(Calculater)
        self.pushButton_six.setGeometry(QtCore.QRect(220, 200, 84, 28))
        self.pushButton_six.setObjectName("pushButton_six")
        self.pushButton_three = QtWidgets.QPushButton(Calculater)
        self.pushButton_three.setGeometry(QtCore.QRect(220, 240, 84, 28))
        self.pushButton_three.setObjectName("pushButton_three")
        self.pushButton_nine = QtWidgets.QPushButton(Calculater)
        self.pushButton_nine.setGeometry(QtCore.QRect(220, 160, 84, 28))
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.pushButton_zero = QtWidgets.QPushButton(Calculater)
        self.pushButton_zero.setGeometry(QtCore.QRect(20, 280, 84, 28))
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.pushButton_sub = QtWidgets.QPushButton(Calculater)
        self.pushButton_sub.setGeometry(QtCore.QRect(320, 240, 84, 28))
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.pushButton_one = QtWidgets.QPushButton(Calculater)
        self.pushButton_one.setGeometry(QtCore.QRect(20, 240, 84, 28))
        self.pushButton_one.setObjectName("pushButton_one")
        self.pushButton_seven = QtWidgets.QPushButton(Calculater)
        self.pushButton_seven.setGeometry(QtCore.QRect(20, 160, 84, 28))
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.pushButton_eight = QtWidgets.QPushButton(Calculater)
        self.pushButton_eight.setGeometry(QtCore.QRect(120, 160, 84, 28))
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.lcdNumber = QtWidgets.QLCDNumber(Calculater)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 30, 484, 60))
        self.lcdNumber.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton_add = QtWidgets.QPushButton(Calculater)
        self.pushButton_add.setGeometry(QtCore.QRect(320, 280, 84, 28))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_two = QtWidgets.QPushButton(Calculater)
        self.pushButton_two.setGeometry(QtCore.QRect(120, 240, 84, 28))
        self.pushButton_two.setObjectName("pushButton_two")
        self.pushButton_four = QtWidgets.QPushButton(Calculater)
        self.pushButton_four.setGeometry(QtCore.QRect(20, 200, 84, 28))
        self.pushButton_four.setObjectName("pushButton_four")
        self.pushButton_mul = QtWidgets.QPushButton(Calculater)
        self.pushButton_mul.setGeometry(QtCore.QRect(320, 160, 84, 28))
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_div = QtWidgets.QPushButton(Calculater)
        self.pushButton_div.setGeometry(QtCore.QRect(320, 200, 84, 28))
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_dot = QtWidgets.QPushButton(Calculater)
        self.pushButton_dot.setGeometry(QtCore.QRect(220, 280, 84, 28))
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_five = QtWidgets.QPushButton(Calculater)
        self.pushButton_five.setGeometry(QtCore.QRect(120, 200, 84, 28))
        self.pushButton_five.setObjectName("pushButton_five")
        self.pushButton_backspace = QtWidgets.QPushButton(Calculater)
        self.pushButton_backspace.setGeometry(QtCore.QRect(420, 240, 84, 28))
        self.pushButton_backspace.setObjectName("pushButton_backspace")
        self.pushButton_clear = QtWidgets.QPushButton(Calculater)
        self.pushButton_clear.setGeometry(QtCore.QRect(420, 200, 84, 28))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_clear_all = QtWidgets.QPushButton(Calculater)
        self.pushButton_clear_all.setGeometry(QtCore.QRect(420, 160, 84, 28))
        self.pushButton_clear_all.setObjectName("pushButton_clear_all")
        self.pushButton_equal = QtWidgets.QPushButton(Calculater)
        self.pushButton_equal.setGeometry(QtCore.QRect(420, 280, 84, 28))
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_double_zero = QtWidgets.QPushButton(Calculater)
        self.pushButton_double_zero.setGeometry(QtCore.QRect(120, 280, 84, 28))
        self.pushButton_double_zero.setObjectName("pushButton_double_zero")
        self.textBrowser = QtWidgets.QTextBrowser(Calculater)
        self.textBrowser.setGeometry(QtCore.QRect(20, 100, 484, 50))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Calculater)
        self.pushButton_seven.clicked.connect(Calculater.on_click)
        self.pushButton_four.clicked.connect(Calculater.on_click)
        self.pushButton_one.clicked.connect(Calculater.on_click)
        self.pushButton_zero.clicked.connect(Calculater.on_click)
        self.pushButton_eight.clicked.connect(Calculater.on_click)
        self.pushButton_five.clicked.connect(Calculater.on_click)
        self.pushButton_two.clicked.connect(Calculater.on_click)
        self.pushButton_double_zero.clicked.connect(Calculater.on_click)
        self.pushButton_nine.clicked.connect(Calculater.on_click)
        self.pushButton_six.clicked.connect(Calculater.on_click)
        self.pushButton_three.clicked.connect(Calculater.on_click)
        self.pushButton_dot.clicked.connect(Calculater.on_click)
        self.pushButton_mul.clicked.connect(Calculater.on_click)
        self.pushButton_div.clicked.connect(Calculater.on_click)
        self.pushButton_sub.clicked.connect(Calculater.on_click)
        self.pushButton_add.clicked.connect(Calculater.on_click)
        self.pushButton_clear_all.clicked.connect(Calculater.on_click)
        self.pushButton_clear.clicked.connect(Calculater.on_click)
        self.pushButton_backspace.clicked.connect(Calculater.on_click)
        self.pushButton_equal.clicked.connect(Calculater.on_click)
        QtCore.QMetaObject.connectSlotsByName(Calculater)

    def retranslateUi(self, Calculater):
        _translate = QtCore.QCoreApplication.translate
        Calculater.setWindowTitle(_translate("Calculater", "Calculater"))
        self.pushButton_six.setText(_translate("Calculater", "6"))
        self.pushButton_three.setText(_translate("Calculater", "3"))
        self.pushButton_nine.setText(_translate("Calculater", "9"))
        self.pushButton_zero.setText(_translate("Calculater", "0"))
        self.pushButton_sub.setText(_translate("Calculater", "-"))
        self.pushButton_one.setText(_translate("Calculater", "1"))
        self.pushButton_seven.setText(_translate("Calculater", "7"))
        self.pushButton_eight.setText(_translate("Calculater", "8"))
        self.pushButton_add.setText(_translate("Calculater", "+"))
        self.pushButton_two.setText(_translate("Calculater", "2"))
        self.pushButton_four.setText(_translate("Calculater", "4"))
        self.pushButton_mul.setText(_translate("Calculater", "×"))
        self.pushButton_div.setText(_translate("Calculater", "/"))
        self.pushButton_dot.setText(_translate("Calculater", "."))
        self.pushButton_five.setText(_translate("Calculater", "5"))
        self.pushButton_backspace.setText(_translate("Calculater", "Backspace"))
        self.pushButton_clear.setText(_translate("Calculater", "Clear"))
        self.pushButton_clear_all.setText(_translate("Calculater", "Clear all"))
        self.pushButton_equal.setText(_translate("Calculater", "="))
        self.pushButton_double_zero.setText(_translate("Calculater", "00"))

