# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calc(object):
    def setupUi(self, Calc):
        Calc.setObjectName("Calc")
        Calc.resize(529, 297)
        self.pushButton_six = QtWidgets.QPushButton(Calc)
        self.pushButton_six.setGeometry(QtCore.QRect(220, 160, 84, 28))
        self.pushButton_six.setObjectName("pushButton_six")
        self.pushButton_three = QtWidgets.QPushButton(Calc)
        self.pushButton_three.setGeometry(QtCore.QRect(220, 200, 84, 28))
        self.pushButton_three.setObjectName("pushButton_three")
        self.pushButton_nine = QtWidgets.QPushButton(Calc)
        self.pushButton_nine.setGeometry(QtCore.QRect(220, 120, 84, 28))
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.pushButton_equal = QtWidgets.QPushButton(Calc)
        self.pushButton_equal.setGeometry(QtCore.QRect(420, 117, 84, 151))
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_zero = QtWidgets.QPushButton(Calc)
        self.pushButton_zero.setGeometry(QtCore.QRect(20, 240, 84, 28))
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.pushButton_sub = QtWidgets.QPushButton(Calc)
        self.pushButton_sub.setGeometry(QtCore.QRect(320, 160, 84, 28))
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.pushButton_one = QtWidgets.QPushButton(Calc)
        self.pushButton_one.setGeometry(QtCore.QRect(20, 200, 84, 28))
        self.pushButton_one.setObjectName("pushButton_one")
        self.pushButton_seven = QtWidgets.QPushButton(Calc)
        self.pushButton_seven.setGeometry(QtCore.QRect(20, 120, 84, 28))
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.pushButton_eight = QtWidgets.QPushButton(Calc)
        self.pushButton_eight.setGeometry(QtCore.QRect(120, 120, 84, 28))
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.lcdNumber = QtWidgets.QLCDNumber(Calc)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 29, 481, 51))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton_double_zero = QtWidgets.QPushButton(Calc)
        self.pushButton_double_zero.setGeometry(QtCore.QRect(120, 240, 84, 28))
        self.pushButton_double_zero.setObjectName("pushButton_double_zero")
        self.pushButton_add = QtWidgets.QPushButton(Calc)
        self.pushButton_add.setGeometry(QtCore.QRect(320, 120, 84, 28))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_two = QtWidgets.QPushButton(Calc)
        self.pushButton_two.setGeometry(QtCore.QRect(120, 200, 84, 28))
        self.pushButton_two.setObjectName("pushButton_two")
        self.pushButton_four = QtWidgets.QPushButton(Calc)
        self.pushButton_four.setGeometry(QtCore.QRect(20, 160, 84, 28))
        self.pushButton_four.setObjectName("pushButton_four")
        self.pushButton_mul = QtWidgets.QPushButton(Calc)
        self.pushButton_mul.setGeometry(QtCore.QRect(320, 200, 84, 28))
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_div = QtWidgets.QPushButton(Calc)
        self.pushButton_div.setGeometry(QtCore.QRect(320, 240, 84, 28))
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_dot = QtWidgets.QPushButton(Calc)
        self.pushButton_dot.setGeometry(QtCore.QRect(220, 240, 84, 28))
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_five = QtWidgets.QPushButton(Calc)
        self.pushButton_five.setGeometry(QtCore.QRect(120, 160, 84, 28))
        self.pushButton_five.setObjectName("pushButton_five")

        self.retranslateUi(Calc)
        self.pushButton_zero.clicked.connect(Calc.on_click)
        self.pushButton_one.clicked.connect(Calc.on_click)
        self.pushButton_four.clicked.connect(Calc.on_click)
        self.pushButton_seven.clicked.connect(Calc.on_click)
        self.pushButton_double_zero.clicked.connect(Calc.on_click)
        self.pushButton_two.clicked.connect(Calc.on_click)
        self.pushButton_five.clicked.connect(Calc.on_click)
        self.pushButton_eight.clicked.connect(Calc.on_click)
        self.pushButton_nine.clicked.connect(Calc.on_click)
        self.pushButton_six.clicked.connect(Calc.on_click)
        self.pushButton_three.clicked.connect(Calc.on_click)
        self.pushButton_dot.clicked.connect(Calc.on_click)
        self.pushButton_add.clicked.connect(Calc.on_click)
        self.pushButton_sub.clicked.connect(Calc.on_click)
        self.pushButton_mul.clicked.connect(Calc.on_click)
        self.pushButton_div.clicked.connect(Calc.on_click)
        self.pushButton_equal.clicked.connect(Calc.on_click)
        QtCore.QMetaObject.connectSlotsByName(Calc)

    def retranslateUi(self, Calc):
        _translate = QtCore.QCoreApplication.translate
        Calc.setWindowTitle(_translate("Calc", "Calc"))
        self.pushButton_six.setText(_translate("Calc", "6"))
        self.pushButton_three.setText(_translate("Calc", "3"))
        self.pushButton_nine.setText(_translate("Calc", "9"))
        self.pushButton_equal.setText(_translate("Calc", "="))
        self.pushButton_zero.setText(_translate("Calc", "0"))
        self.pushButton_sub.setText(_translate("Calc", "-"))
        self.pushButton_one.setText(_translate("Calc", "1"))
        self.pushButton_seven.setText(_translate("Calc", "7"))
        self.pushButton_eight.setText(_translate("Calc", "8"))
        self.pushButton_double_zero.setText(_translate("Calc", "00"))
        self.pushButton_add.setText(_translate("Calc", "+"))
        self.pushButton_two.setText(_translate("Calc", "2"))
        self.pushButton_four.setText(_translate("Calc", "4"))
        self.pushButton_mul.setText(_translate("Calc", "×"))
        self.pushButton_div.setText(_translate("Calc", "/"))
        self.pushButton_dot.setText(_translate("Calc", "."))
        self.pushButton_five.setText(_translate("Calc", "5"))

